//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R59_M7_Class_01_Work_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesId { get; set; }
        public System.DateTime Date { get; set; }
        public int SellerId { get; set; }
        public int Quantity { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
